# Generated by Django 6.1.2 on 2026-10-07 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawJobPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('raw_data', models.JSONField()),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fetched_at', models.DateTimeField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_payloads', to='intelligence.job')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'fetched_at'], name='ingestion_r_source_3186fd_idx')],
            },
        ),
    ]
