# Generated by Django 6.1.2 on 2026-10-07 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normalised_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('normalised_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_text', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('normalised_country', models.CharField(blank=True, max_length=100)),
                ('normalised_city', models.CharField(blank=True, max_length=100)),
                ('is_remote', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'city'], name='intelligenc_country_1e1d9e_idx')],
                'unique_together': {('normalised_country', 'normalised_city')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(max_length=100)),
                ('source_id', models.CharField(max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('published_date', models.DateField(blank=True, db_index=True, null=True)),
                ('salary_text', models.CharField(blank=True, max_length=255)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10)),
                ('contract_type', models.CharField(blank=True, max_length=50)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.company')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.location')),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('extraction_method', models.CharField(blank=True, max_length=50)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.skill')),
            ],
            options={
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, through='intelligence.JobSkill', to='intelligence.skill'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source', 'source_id'], name='intelligenc_source_79d5ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('source', 'source_id')},
        ),
    ]
